config/routes.rb
Rails.application.routes.draw do
  get 'working_days/new'
  resources :working_days
  resources :slots do 
		patch 'select',	on: :member
	end
  root 'working_days#index'
end

app/models/slot.rb
class Slot < ActiveRecord::Base
  belongs_to :working_day
end

app/models/working_day.rb
class WorkingDay < ActiveRecord::Base
  has_many :slots, :dependent => :destroy

  def slots_number
    # binding.pry
    total_minutes = (end_of_day - start_of_day) / 60
    (total_minutes / divider_partition_hour).to_i
  end

  def create_slots
    i = 0
    while i < slots_number
      # binding.pry
      start = start_of_day + (divider_partition_hour * i ) * 60
      i += 1
      Slot.create(start_time: start, end_time: start + ( divider_partition_hour * 60 ), selected: false, working_day_id: id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  def index
    @slots = Slot.all
  end
  def show
    @slot = Slot.find(params[:id])
  end

  def select
    @slot = Slot.find(params[:id])
    @slot.update_attributes(selected: true)
		redirect_to @slot
  end
end

app/controllers/working_days_controller.rb
class WorkingDaysController < ApplicationController
  def index
    @working_days = WorkingDay.all
  end

  def new
    @working_day = WorkingDay.new
    @slot = Slot.new
  end

  def show
    @working_day = WorkingDay.find(params[:id])
    @slots = Slot.all
  end

  def create
    @working_day = WorkingDay.new(working_parmas)

    if @working_day.save
      @working_day.create_slots
      # binding.pry
      redirect_to working_days_path(@working_day)
    else
      render 'new'
    end
  end

  private

  def working_parmas
    params.require(:working_day).permit(:start_of_day, :end_of_day, :divider_partition_hour, :slot_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/working_days_helper.rb
module WorkingDaysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <ul>
      <li><%= link_to "Slots", slots_path %></li>
      <li><%= link_to "Home", root_path %></li>
    </ul>
  </header>

<%= yield %>

</body>
</html>

app/views/slots/index.html.erb
<h1>Hi</h1>
<% @slots.each do |s| %>
  <%= button_to select_slot_path(s), method: :patch do %>
		<%= s.start_time.strftime("%A" " " "%H" ":" "%M") %> to
    <%= s.end_time.strftime("%H" ":" "%M") %>
	<% end %>
<% end %>

app/views/slots/show.html.erb
<div class="row">
  <%= @slot.start_time.strftime("%A" " " "%H" ":" "%M") %> to <%= @slot.end_time.strftime("%H" ":" "%M") %>
</div>

app/views/working_days/index.html.erb
<% @working_days.each do |working_day| %>
  <%= link_to working_day_path(working_day) do %>
    <h4 class="non"><%= working_day.start_of_day.strftime("%A" " " "%H" ":" "%M" " " "%D " "%Y") %> to <%= working_day.end_of_day.strftime(" " "%H" ":" "%M" " " "%Y") %></h4>
  <% end %>
<% end %>
<hr />

<h2><%= link_to "Create a list of slots", working_days_new_path, class: 'btn btn-primary' %></h2>

app/views/working_days/new.html.erb
<%= simple_form_for @working_day do |f| %>
  <%= f.input :start_of_day,:as => :time_picker,
              input_html: {data: {date_options: { minDate: Time.zone.now }}} %>
  <%= f.input :end_of_day, :as => :time_picker  %>
  <%= f.input :divider_partition_hour %>
  <%= f.submit 'Create', :class => 'btn btn-primary' %>
<% end %>

app/views/working_days/show.html.erb
<h1>Show page</h1>

<h4><%= @working_day.start_of_day %></h4>
<h4><%= @working_day.end_of_day %></h4>
<% @slots.each do |slot| %>
  <h4><%= slot.start_time.strftime("%H" ":" "%M") %> to
  <%= slot.end_time.strftime("%H" ":" "%M") %></h4>
<% end %>